controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - rear_right_joint_1
      - rear_right_joint_2
      - rear_right_joint_3
      - rear_left_joint_1
      - rear_left_joint_2
      - rear_left_joint_3
      - front_right_joint_1
      - front_right_joint_2
      - front_right_joint_3
      - front_left_joint_1
      - front_left_joint_2
      - front_left_joint_3
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    interpolate_from_desired_state: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03

    
    
