controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Base-Body_Revolute-41
      - Actuator-1_Revolute-61
      - upper-leg-1_Revolute-68
      - Base-Body_Revolute-62
      - Actuator-2_Revolute-63
      - upper-leg-2_Revolute-69
      - Base-Body_Revolute-64
      - Actuator-3_Revolute-65
      - upper-leg-3_Revolute-70
      - Base-Body_Revolute-66
      - Actuator-4_Revolute-67
      - upper-leg-4_Revolute-71
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    interpolate_from_desired_state: true
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      joint1:
        trajectory: 0.05
        goal: 0.03

    
    
